"""initial_schema

Revision ID: 215a7f6e890a
Revises: 
Create Date: 2026-06-19 17:00:39.073261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215a7f6e890a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_index(op.f('ix_users_building_id'), 'users', ['building_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_building_id'), table_name='users')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    # ### end Alembic commands ###
