"""Add Visitor model

Revision ID: 8cba9d80fee2
Revises: 215a7f6e890a
Create Date: 2026-06-20 05:24:07.876295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cba9d80fee2'
down_revision: Union[str, Sequence[str], None] = '215a7f6e890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expected_arrival', sa.Date(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_building_id'), 'visitors', ['building_id'], unique=False)
    op.create_index(op.f('ix_visitors_host_id'), 'visitors', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_host_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_building_id'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
