"""create amenity and booking tables

Revision ID: ff626c9eddb9
Revises: 49a866710e29
Create Date: 2026-06-23 15:23:44.876962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff626c9eddb9'
down_revision: Union[str, Sequence[str], None] = '49a866710e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rules', sa.String(length=1000), nullable=True),
    sa.Column('booking_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_building_id'), 'amenities', ['building_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('amenity_id', sa.String(length=36), nullable=False),
    sa.Column('resident_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_amenity_id'), 'bookings', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_bookings_building_id'), 'bookings', ['building_id'], unique=False)
    op.create_index(op.f('ix_bookings_resident_id'), 'bookings', ['resident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_resident_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_building_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_amenity_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_amenities_building_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
